### ISSUE TITLE
Planes Setup

### ISSUE THREAD

**Issue by haydarkaraoglu** [CMU-Quake/hercules#8]
As far as I know, there are two versions of routine for setting up and printing planes which have prefixes 'New' and 'Old'. The choice is done depending on the env variable IO_PES. Does anyone know where and how this variable is defined?

**Comment by ricardotaborda** [comment]
[make sure you read all the answer]

All, here is the story about the planes module.  planes were originally designed to be written to disk by PE0.  At some point around 2008--2009, it became evident that PE0 could easily run out of memory (OOM) and that this approach was not sustainable.  

John Urbanic, from PSC, was working closely with us at the time and was given the task of changing the planes module structure on how to write planes to overcome the potential OOM issue.  My recollection is that he first rewrote some of the code in the original planes module, and then did the major modifications that led to the current version.

In principle, the trick works like this.  If one defines an environmental variable 

``` bash
IO_PES=n 
```

in the jobscript (or the console prior to executing the program), with `n~=0`, then Hercules picks that up and takes a detour on dealing with the planes.  If, on the other hand, `n=0`, then Hercules operates with planes as it used with PE0 handling all the work.

The option in which `IO_PES` is not defined is the default option.  Within the code, that means that when Hercules enters the `planes` module, it will follow all the methods that are called `"Old"_<something>`.  On the other hand, if you defined `IO_PES` an integer different than zero, then the code will take the detour and operate with all the `"New"_<something>` methods.

Having said that.  John was the only person to test the "new" implementation of the planes.  I tried once and did not work, but had no time to think why.  It may have been I used it wrong.  

If you are reading this entry, it is likely that you want or need to modify something in planes.  Until someone tests the "new " detour thoroughly, the ideal way to proceed is to do such changes in both the "new" and the "old" code paths, but you are responsible only for debugging and testing the "old" path, which is the default.
